import { Meeting, Speaker } from './types';

// Asset paths
import meetingVideoFeed from './assets/images/meeting_video_feed_1790933819582.jpg';
import avatarMarcus from './assets/images/avatar_marcus_vance_1790933835889.jpg';
import avatarElena from './assets/images/avatar_elena_rostova_1790933849719.jpg';

export const SPEAKERS: Record<string, Speaker> = {
  elena: {
    id: 'spk-1',
    name: 'Elena Rostova',
    role: 'VP of Product',
    email: 'elena.rostova@meetsync.corp',
    avatarUrl: avatarElena,
    department: 'Product Strategy',
    color: '#1D70F5',
  },
  marcus: {
    id: 'spk-2',
    name: 'Marcus Vance',
    role: 'Principal Systems Architect',
    email: 'marcus.vance@meetsync.corp',
    avatarUrl: avatarMarcus,
    department: 'Infrastructure',
    color: '#067330',
  },
  sarah: {
    id: 'spk-3',
    name: 'Sarah Chen',
    role: 'Head of Design & UX',
    email: 'sarah.chen@meetsync.corp',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Design Org',
    color: '#8B5CF6',
  },
  david: {
    id: 'spk-4',
    name: 'David Kim',
    role: 'VP of Engineering',
    email: 'david.kim@meetsync.corp',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Core Engineering',
    color: '#D97706',
  },
};

export const PRIMARY_MEETING: Meeting = {
  id: 'mtg-q4-strategy',
  title: 'Q4 Product Strategy Sync',
  date: '2026-10-02',
  time: '10:00 AM - 10:45 AM EST',
  durationSeconds: 2700, // 45 mins
  organizer: 'Elena Rostova',
  department: 'Executive Product & Eng Guild',
  status: 'Ready for Review',
  attendees: [SPEAKERS.elena, SPEAKERS.marcus, SPEAKERS.sarah, SPEAKERS.david],
  mediaThumbnailUrl: meetingVideoFeed,
  summary:
    'Strategic alignment on Q4 milestones, core architectural consolidation to GraphQL Federation Gateway, mobile offline synchronization guarantees, and finalizing the SOC2 Type II compliance audit schedule.',
  keyTakeaways: [
    'Confirmed migration of core public API endpoints to GraphQL Federation Gateway with zero-downtime canary deployment beginning November 12.',
    'Approved Sarah’s streamlined design system token migration for enterprise white-labeling, prioritizing contrast ratio AA compliance.',
    'Agreed on CRDT-based offline state resolution algorithm for mobile client v2.4 with fallback to server-authoritative timestamps.',
    'Engineering headcount allocation approved: 3 Senior Distributed Systems Engineers allocated to core multi-tenant security isolation.',
    'Locked next milestone date: Release Candidate 1 (RC1) scheduled for December 4th demo to Fortune 500 lighthouse customers.',
  ],
  transcript: [
    {
      id: 'seg-1',
      speakerId: 'spk-1',
      speakerName: 'Elena Rostova',
      startSeconds: 0,
      endSeconds: 42,
      text: 'Good morning everyone. Welcome to our Q4 Product Strategy Sync. Today our primary goal is to lock down our platform roadmap, resolve the gateway architectural fork, and ensure our commitments to enterprise customers remain rock-solid.',
      sentiment: 'positive',
      confidenceScore: 0.99,
    },
    {
      id: 'seg-2',
      speakerId: 'spk-4',
      speakerName: 'David Kim',
      startSeconds: 43,
      endSeconds: 118,
      text: 'Thanks Elena. From an engineering standpoint, our sprint velocity in Q3 was strong at 94% story point completion. However, latency metrics on our nested REST endpoints spiked 32% under synthetic 50k concurrent connection load tests last week.',
      sentiment: 'neutral',
      confidenceScore: 0.97,
    },
    {
      id: 'seg-3',
      speakerId: 'spk-2',
      speakerName: 'Marcus Vance',
      startSeconds: 119,
      endSeconds: 215,
      text: 'I have the telemetry breakdown here. The latency bottleneck isn’t the database layer; it is the 8 sequential HTTP roundtrips between microservices during client hydrate calls. If we unify beneath a GraphQL Federation gateway, we can collapse those into a single sub-graph query plan and drop p99 latency under 85ms.',
      sentiment: 'positive',
      confidenceScore: 0.98,
    },
    {
      id: 'seg-4',
      speakerId: 'spk-1',
      speakerName: 'Elena Rostova',
      startSeconds: 216,
      endSeconds: 275,
      text: 'Marcus, how does this affect our third-party developer integrations? We already have 14 tier-one enterprise partners relying on the v1 REST contract.',
      sentiment: 'neutral',
      confidenceScore: 0.96,
    },
    {
      id: 'seg-5',
      speakerId: 'spk-2',
      speakerName: 'Marcus Vance',
      startSeconds: 276,
      endSeconds: 360,
      text: 'We will maintain full backward compatibility via an Envoy reverse-proxy wrapper. Old REST routes will seamlessly proxy into GraphQL queries under the hood with zero schema breaking changes. No client code changes required.',
      sentiment: 'positive',
      isKeyDecision: true,
      confidenceScore: 0.99,
    },
    {
      id: 'seg-6',
      speakerId: 'spk-3',
      speakerName: 'Sarah Chen',
      startSeconds: 361,
      endSeconds: 450,
      text: 'From the design and user experience front, our enterprise customer interviews highlighted accessibility as a core blocker for government tenders. We need strict WCAG AA contrast compliance across the entire white-label palette before November 15.',
      sentiment: 'neutral',
      confidenceScore: 0.98,
    },
    {
      id: 'seg-7',
      speakerId: 'spk-1',
      speakerName: 'Elena Rostova',
      startSeconds: 451,
      endSeconds: 520,
      text: 'Understood. Sarah, let’s make that an explicit P0 deliverable. Are your updated design tokens ready for the frontend engineers to consume in npm?',
      sentiment: 'positive',
      confidenceScore: 0.97,
    },
    {
      id: 'seg-8',
      speakerId: 'spk-3',
      speakerName: 'Sarah Chen',
      startSeconds: 521,
      endSeconds: 610,
      text: 'Yes, the design token npm package @meetsync/tokens v2 is ready for canary deployment. I will hand that over to David’s web team by this Friday afternoon.',
      sentiment: 'positive',
      confidenceScore: 0.99,
    },
    {
      id: 'seg-9',
      speakerId: 'spk-4',
      speakerName: 'David Kim',
      startSeconds: 611,
      endSeconds: 710,
      text: 'Now on mobile offline sync: Field reps working in industrial sites lose connectivity for up to 4 hours. When they reconnect, we see document version collisions in SQLite.',
      sentiment: 'skeptical',
      confidenceScore: 0.95,
    },
    {
      id: 'seg-10',
      speakerId: 'spk-2',
      speakerName: 'Marcus Vance',
      startSeconds: 711,
      endSeconds: 840,
      text: 'We evaluated Automerge and Yjs. We agreed that adopting a lightweight state-based CRDT format for collaborative minutes and task checklists solves the conflict resolution deterministically without needing server arbitration locks.',
      sentiment: 'positive',
      isKeyDecision: true,
      confidenceScore: 0.98,
    },
    {
      id: 'seg-11',
      speakerId: 'spk-1',
      speakerName: 'Elena Rostova',
      startSeconds: 841,
      endSeconds: 960,
      text: 'Let’s formalize that decision. Marcus, please document the CRDT architecture RFC and have it signed off by October 9th. David, what is our target for RC1 internal test flights?',
      sentiment: 'positive',
      confidenceScore: 0.97,
    },
    {
      id: 'seg-12',
      speakerId: 'spk-4',
      speakerName: 'David Kim',
      startSeconds: 961,
      endSeconds: 1080,
      text: 'If Marcus has the gateway proof-of-concept ready by October 24th, we can bundle the CRDT mobile engine and cut RC1 on December 4th. That gives QA three full regression cycles before end-of-year enterprise freeze.',
      sentiment: 'positive',
      isKeyDecision: true,
      confidenceScore: 0.99,
    },
    {
      id: 'seg-13',
      speakerId: 'spk-3',
      speakerName: 'Sarah Chen',
      startSeconds: 1081,
      endSeconds: 1195,
      text: 'I will also sync with the sales engineering team on the customer demo sandbox so the new dark mode and high-contrast icy blue theme can be previewed during executive buyer sessions.',
      sentiment: 'positive',
      confidenceScore: 0.98,
    },
    {
      id: 'seg-14',
      speakerId: 'spk-1',
      speakerName: 'Elena Rostova',
      startSeconds: 1196,
      endSeconds: 1320,
      text: 'Excellent. Let’s review our action items: Marcus on Gateway RFC & proxy layer; Sarah on design tokens v2; David on QA staffing; and I will draft the customer communications for our advisory council.',
      sentiment: 'positive',
      confidenceScore: 0.99,
    },
  ],
  actionItems: [
    {
      id: 'act-1',
      title: 'Publish GraphQL Federation Gateway RFC & Envoy Compatibility Spec',
      assignee: 'Marcus Vance',
      assigneeAvatar: avatarMarcus,
      dueDate: '2026-10-09',
      priority: 'high',
      completed: false,
      originTimestamp: 276,
      relatedDecisionId: 'dec-1',
    },
    {
      id: 'act-2',
      title: 'Publish @meetsync/tokens v2 with WCAG AA compliance tokens',
      assignee: 'Sarah Chen',
      assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      dueDate: '2026-10-06',
      priority: 'high',
      completed: true,
      originTimestamp: 521,
    },
    {
      id: 'act-3',
      title: 'Benchmark CRDT client library footprint against SQLite mobile engine',
      assignee: 'David Kim',
      assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      dueDate: '2026-10-14',
      priority: 'medium',
      completed: false,
      originTimestamp: 711,
      relatedDecisionId: 'dec-2',
    },
    {
      id: 'act-4',
      title: 'Prepare Fortune 500 executive briefing deck for December 4 RC1 demo',
      assignee: 'Elena Rostova',
      assigneeAvatar: avatarElena,
      dueDate: '2026-10-18',
      priority: 'high',
      completed: false,
      originTimestamp: 1196,
      relatedDecisionId: 'dec-3',
    },
    {
      id: 'act-5',
      title: 'Audit SOC2 Type II cloud perimeter access logs for Q3 compliance sign-off',
      assignee: 'Marcus Vance',
      assigneeAvatar: avatarMarcus,
      dueDate: '2026-10-22',
      priority: 'medium',
      completed: false,
      originTimestamp: 841,
    },
  ],
  decisions: [
    {
      id: 'dec-1',
      code: 'DEC-104',
      statement: 'Adopt GraphQL Federation Gateway while preserving REST v1 contracts via an Envoy reverse proxy layer',
      confidenceScore: 98.4,
      ragDistance: 0.08,
      citationSegmentId: 'seg-5',
      citationTimestamp: 276,
      citationQuote: 'We will maintain full backward compatibility via an Envoy reverse-proxy wrapper. Old REST routes will seamlessly proxy into GraphQL queries under the hood with zero schema breaking changes.',
      status: 'verified',
      category: 'Architecture',
      consensus: {
        'Marcus Vance': 'Proposed',
        'David Kim': 'Approved',
        'Elena Rostova': 'Approved',
        'Sarah Chen': 'Neutral',
      },
      impactedSystems: ['API Gateway', 'Envoy Service Mesh', 'Mobile Client', 'Web App Core'],
    },
    {
      id: 'dec-2',
      code: 'DEC-105',
      statement: 'Implement Conflict-Free Replicated Data Types (CRDTs) for offline-first mobile synchronizations',
      confidenceScore: 95.8,
      ragDistance: 0.12,
      citationSegmentId: 'seg-10',
      citationTimestamp: 711,
      citationQuote: 'We agreed that adopting a lightweight state-based CRDT format for collaborative minutes and task checklists solves the conflict resolution deterministically without needing server arbitration locks.',
      status: 'verified',
      category: 'Architecture',
      consensus: {
        'Marcus Vance': 'Proposed',
        'David Kim': 'Approved',
        'Elena Rostova': 'Approved',
        'Sarah Chen': 'Neutral',
      },
      impactedSystems: ['Mobile Offline Storage', 'Sync Worker', 'Collaborative Editor'],
    },
    {
      id: 'dec-3',
      code: 'DEC-106',
      statement: 'Target December 4, 2026 for Release Candidate 1 (RC1) internal milestone ahead of holiday freeze',
      confidenceScore: 99.1,
      ragDistance: 0.05,
      citationSegmentId: 'seg-12',
      citationTimestamp: 961,
      citationQuote: 'If Marcus has the gateway proof-of-concept ready by October 24th, we can bundle the CRDT mobile engine and cut RC1 on December 4th.',
      status: 'verified',
      category: 'Product',
      consensus: {
        'David Kim': 'Proposed',
        'Elena Rostova': 'Approved',
        'Marcus Vance': 'Approved',
        'Sarah Chen': 'Approved',
      },
      impactedSystems: ['CI/CD Pipeline', 'Product Launch Milestone', 'Partner Sandbox'],
    },
    {
      id: 'dec-4',
      code: 'DEC-107',
      statement: 'Enforce WCAG AA contrast compliance across all custom theme palettes prior to November 15 release',
      confidenceScore: 94.2,
      ragDistance: 0.14,
      citationSegmentId: 'seg-6',
      citationTimestamp: 361,
      citationQuote: 'We need strict WCAG AA contrast compliance across the entire white-label palette before November 15.',
      status: 'verified',
      category: 'Go-to-Market',
      consensus: {
        'Sarah Chen': 'Proposed',
        'Elena Rostova': 'Approved',
        'David Kim': 'Approved',
        'Marcus Vance': 'Neutral',
      },
      impactedSystems: ['Design Tokens', 'Design System CSS', 'Brand Configurator'],
    },
  ],
  sentimentTimeline: [
    { timeLabel: '00:00', minute: 0, positive: 70, neutral: 25, skeptical: 5 },
    { timeLabel: '05:00', minute: 5, positive: 50, neutral: 35, skeptical: 15 },
    { timeLabel: '10:00', minute: 10, positive: 82, neutral: 14, skeptical: 4 },
    { timeLabel: '15:00', minute: 15, positive: 78, neutral: 18, skeptical: 4 },
    { timeLabel: '20:00', minute: 20, positive: 45, neutral: 30, skeptical: 25 },
    { timeLabel: '25:00', minute: 25, positive: 88, neutral: 10, skeptical: 2 },
    { timeLabel: '30:00', minute: 30, positive: 92, neutral: 6, skeptical: 2 },
    { timeLabel: '35:00', minute: 35, positive: 85, neutral: 12, skeptical: 3 },
    { timeLabel: '40:00', minute: 40, positive: 90, neutral: 8, skeptical: 2 },
  ],
  speakerAirtime: [
    { name: 'Elena Rostova', percentage: 38, durationSeconds: 1026, color: '#1D70F5' },
    { name: 'Marcus Vance', percentage: 28, durationSeconds: 756, color: '#067330' },
    { name: 'David Kim', percentage: 20, durationSeconds: 540, color: '#D97706' },
    { name: 'Sarah Chen', percentage: 14, durationSeconds: 378, color: '#8B5CF6' },
  ],
};

export const RECENT_MEETINGS: Meeting[] = [
  PRIMARY_MEETING,
  {
    id: 'mtg-sso-arch',
    title: 'Enterprise SSO & SCIM Directory Architecture Review',
    date: '2026-10-01',
    time: '2:00 PM - 2:45 PM EST',
    durationSeconds: 2700,
    organizer: 'Marcus Vance',
    department: 'Security & Identity',
    status: 'Approved',
    attendees: [SPEAKERS.marcus, SPEAKERS.david],
    mediaThumbnailUrl: meetingVideoFeed,
    summary: 'Architectural evaluation of Okta, Azure AD, and PingFederate automated SCIM user de-provisioning hooks.',
    keyTakeaways: [
      'Standardized on OAuth 2.0 PKCE flow with signed JWT bearer tokens for identity assertion.',
      'Configured automated JIT user provisioning for enterprise enterprise domains.',
    ],
    transcript: [
      {
        id: 'sso-1',
        speakerId: 'spk-2',
        speakerName: 'Marcus Vance',
        startSeconds: 0,
        endSeconds: 60,
        text: 'Reviewing our SCIM 2.0 endpoint specifications. We need to handle bulk user sync without timeout on 10,000 seat imports.',
        sentiment: 'neutral',
        confidenceScore: 0.99,
      },
    ],
    actionItems: [
      {
        id: 'act-sso-1',
        title: 'Complete Okta Integration Network verification submission',
        assignee: 'Marcus Vance',
        assigneeAvatar: avatarMarcus,
        dueDate: '2026-10-15',
        priority: 'high',
        completed: true,
        originTimestamp: 30,
      },
    ],
    decisions: [
      {
        id: 'dec-sso-1',
        code: 'DEC-103',
        statement: 'Mandate SCIM 2.0 schema for all tier-1 enterprise automated user provisioning',
        confidenceScore: 97.2,
        ragDistance: 0.09,
        citationSegmentId: 'sso-1',
        citationTimestamp: 25,
        citationQuote: 'Standardized on OAuth 2.0 PKCE flow with signed JWT bearer tokens for identity assertion.',
        status: 'verified',
        category: 'Architecture',
        consensus: { 'Marcus Vance': 'Proposed', 'David Kim': 'Approved' },
        impactedSystems: ['Auth Service', 'SCIM Controller'],
      },
    ],
    sentimentTimeline: [
      { timeLabel: '00:00', minute: 0, positive: 65, neutral: 30, skeptical: 5 },
      { timeLabel: '15:00', minute: 15, positive: 80, neutral: 15, skeptical: 5 },
      { timeLabel: '30:00', minute: 30, positive: 85, neutral: 12, skeptical: 3 },
    ],
    speakerAirtime: [
      { name: 'Marcus Vance', percentage: 65, durationSeconds: 1755, color: '#067330' },
      { name: 'David Kim', percentage: 35, durationSeconds: 945, color: '#D97706' },
    ],
  },
  {
    id: 'mtg-design-handoff',
    title: 'Mobile UX Overhaul Handoff & Accessibility Audit',
    date: '2026-09-29',
    time: '11:00 AM - 11:30 AM EST',
    durationSeconds: 1800,
    organizer: 'Sarah Chen',
    department: 'Design Org',
    status: 'Approved',
    attendees: [SPEAKERS.sarah, SPEAKERS.elena],
    mediaThumbnailUrl: meetingVideoFeed,
    summary: 'Design audit of mobile bottom drawer navigation, touch target enforcement (min 44x44px), and voice caption layouts.',
    keyTakeaways: [
      'All touch targets upgraded to minimum 44px on mobile viewport.',
      'Dynamic typography scaling enabled for iOS Dynamic Type & Android system font scaling.',
    ],
    transcript: [
      {
        id: 'des-1',
        speakerId: 'spk-3',
        speakerName: 'Sarah Chen',
        startSeconds: 0,
        endSeconds: 50,
        text: 'All interactive components now satisfy the 44px tap target requirements across both phone and tablet breakpoints.',
        sentiment: 'positive',
        confidenceScore: 0.98,
      },
    ],
    actionItems: [
      {
        id: 'act-des-1',
        title: 'Run automated accessibility tests in Cypress mobile suite',
        assignee: 'Sarah Chen',
        assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        dueDate: '2026-10-08',
        priority: 'medium',
        completed: true,
        originTimestamp: 20,
      },
    ],
    decisions: [
      {
        id: 'dec-des-1',
        code: 'DEC-102',
        statement: 'Standardize bottom sheet drawers for secondary filters on mobile devices',
        confidenceScore: 96.0,
        ragDistance: 0.11,
        citationSegmentId: 'des-1',
        citationTimestamp: 15,
        citationQuote: 'All interactive components now satisfy the 44px tap target requirements.',
        status: 'verified',
        category: 'Product',
        consensus: { 'Sarah Chen': 'Proposed', 'Elena Rostova': 'Approved' },
        impactedSystems: ['Mobile UI Library'],
      },
    ],
    sentimentTimeline: [
      { timeLabel: '00:00', minute: 0, positive: 75, neutral: 20, skeptical: 5 },
      { timeLabel: '15:00', minute: 15, positive: 90, neutral: 8, skeptical: 2 },
    ],
    speakerAirtime: [
      { name: 'Sarah Chen', percentage: 70, durationSeconds: 1260, color: '#8B5CF6' },
      { name: 'Elena Rostova', percentage: 30, durationSeconds: 540, color: '#1D70F5' },
    ],
  },
  {
    id: 'mtg-q3-retro',
    title: 'Q3 Infrastructure Reliability Retrospective',
    date: '2026-09-24',
    time: '3:00 PM - 4:00 PM EST',
    durationSeconds: 3600,
    organizer: 'David Kim',
    department: 'Core Engineering',
    status: 'Archived',
    attendees: [SPEAKERS.david, SPEAKERS.marcus, SPEAKERS.elena],
    mediaThumbnailUrl: meetingVideoFeed,
    summary: 'Post-mortem on August network partition incident and database read replica failover automation analysis.',
    keyTakeaways: [
      'Automated DNS failover time reduced from 4.5 minutes to 18 seconds using healthcheck-routed Anycast IP.',
      'Zero customer data loss reported during high-availability drill.',
    ],
    transcript: [
      {
        id: 'ret-1',
        speakerId: 'spk-4',
        speakerName: 'David Kim',
        startSeconds: 0,
        endSeconds: 45,
        text: 'Overall Q3 uptime finished at 99.982%, surpassing our 99.95% customer SLA.',
        sentiment: 'positive',
        confidenceScore: 0.99,
      },
    ],
    actionItems: [
      {
        id: 'act-ret-1',
        title: 'Publish customer transparency incident post-mortem on trust portal',
        assignee: 'David Kim',
        assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        dueDate: '2026-10-02',
        priority: 'low',
        completed: true,
        originTimestamp: 15,
      },
    ],
    decisions: [
      {
        id: 'dec-ret-1',
        code: 'DEC-101',
        statement: 'Implement Anycast BGP routing with automated health probes for failover',
        confidenceScore: 99.4,
        ragDistance: 0.04,
        citationSegmentId: 'ret-1',
        citationTimestamp: 10,
        citationQuote: 'Automated DNS failover time reduced from 4.5 minutes to 18 seconds.',
        status: 'verified',
        category: 'Architecture',
        consensus: { 'David Kim': 'Approved', 'Marcus Vance': 'Proposed', 'Elena Rostova': 'Approved' },
        impactedSystems: ['Cloud Load Balancers', 'Edge DNS'],
      },
    ],
    sentimentTimeline: [
      { timeLabel: '00:00', minute: 0, positive: 50, neutral: 40, skeptical: 10 },
      { timeLabel: '30:00', minute: 30, positive: 75, neutral: 20, skeptical: 5 },
      { timeLabel: '60:00', minute: 60, positive: 90, neutral: 8, skeptical: 2 },
    ],
    speakerAirtime: [
      { name: 'David Kim', percentage: 50, durationSeconds: 1800, color: '#D97706' },
      { name: 'Marcus Vance', percentage: 35, durationSeconds: 1260, color: '#067330' },
      { name: 'Elena Rostova', percentage: 15, durationSeconds: 540, color: '#1D70F5' },
    ],
  },
];
