
import { Meeting, MeetingDecision, ActionItem } from '../types';
import { formatDuration } from './time';

/**
 * Triggers a real browser download for a Blob
 */
export function triggerFileDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports decision traceability audit records to a structured CSV file
 */
export function exportDecisionsToCSV(meeting: Meeting): string {
  const headers = [
    'Decision Code',
    'Statement',
    'Category',
    'Status',
    'Confidence Score (%)',
    'RAG Cosine Distance',
    'Citation Timestamp',
    'Citation Seconds',
    'Citation Quote',
    'Consensus Stances',
    'Impacted Infrastructure',
    'Meeting Title',
    'Meeting Date',
    'Meeting Organizer',
  ];

  const escapeCSV = (val: string | number | undefined | null): string => {
    if (val === undefined || val === null) return '""';
    const str = String(val).replace(/"/g, '""');
    return `"${str}"`;
  };

  const rows = meeting.decisions.map((dec) => {
    const consensusStr = Object.entries(dec.consensus || {})
      .map(([person, stance]) => `${person}: ${stance}`)
      .join('; ');
    const systemsStr = (dec.impactedSystems || []).join('; ');

    return [
      escapeCSV(dec.code),
      escapeCSV(dec.statement),
      escapeCSV(dec.category),
      escapeCSV(dec.status),
      escapeCSV(dec.confidenceScore),
      escapeCSV(dec.ragDistance),
      escapeCSV(formatDuration(dec.citationTimestamp)),
      escapeCSV(dec.citationTimestamp),
      escapeCSV(dec.citationQuote),
      escapeCSV(consensusStr),
      escapeCSV(systemsStr),
      escapeCSV(meeting.title),
      escapeCSV(meeting.date),
      escapeCSV(meeting.organizer),
    ].join(',');
  });

  const csvContent = [headers.join(','), ...rows].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  
  const sanitizedTitle = meeting.title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const dateStr = new Date().toISOString().slice(0, 10);
  const filename = `Decision_Traceability_Audit_${sanitizedTitle}_${dateStr}.csv`;
  
  triggerFileDownload(blob, filename);
  return filename;
}

/**
 * Exports complete Minutes of Meeting (MOM) to Markdown
 */
export function exportMOMToMarkdown(meeting: Meeting): string {
  const lines: string[] = [
    `# ${meeting.title} — Executive Minutes of Meeting`,
    ``,
    `- **Date**: ${meeting.date} ${meeting.time}`,
    `- **Department**: ${meeting.department}`,
    `- **Organizer / Host**: ${meeting.organizer}`,
    `- **Duration**: ${formatDuration(meeting.durationSeconds)}`,
    `- **Status**: ${meeting.status}`,
    ``,
    `## Executive Summary`,
    `${meeting.summary}`,
    ``,
    `## Key Strategic Takeaways`,
    ...meeting.keyTakeaways.map((t) => `- ${t}`),
    ``,
    `## Action Items & Ownership`,
    `| Task | Assignee | Priority | Due Date | Status | Origin Time |`,
    `| :--- | :--- | :--- | :--- | :--- | :--- |`,
    ...meeting.actionItems.map(
      (a) =>
        `| ${a.title.replace(/\|/g, '-')} | ${a.assignee} | ${a.priority.toUpperCase()} | ${a.dueDate} | ${a.completed ? 'COMPLETED' : 'OPEN'} | ${a.originTimestamp ? formatDuration(a.originTimestamp) : 'N/A'} |`
    ),
    ``,
    `## Decision Traceability Matrix (RAG Audit)`,
    `| Code | Decision Statement | Category | Confidence | Status | Audio Timestamp |`,
    `| :--- | :--- | :--- | :--- | :--- | :--- |`,
    ...meeting.decisions.map(
      (d) =>
        `| **${d.code}** | ${d.statement.replace(/\|/g, '-')} | ${d.category} | ${d.confidenceScore}% | ${d.status.toUpperCase()} | [${formatDuration(d.citationTimestamp)}] |`
    ),
    ``,
    `### Decision Citation Evidence`,
    ...meeting.decisions.map(
      (d) =>
        `#### ${d.code}: ${d.statement}\n> "${d.citationQuote}"\n- **Consensus**: ${Object.entries(d.consensus).map(([k, v]) => `${k} (${v})`).join(', ')}\n- **Impacted Systems**: ${d.impactedSystems.join(', ')}\n`
    ),
    ``,
    `---`,
    `*Generated by MeetSync AI Platform • Verifiable Executive Intelligence*`,
  ];

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const sanitizedTitle = meeting.title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const filename = `${sanitizedTitle}_MOM_${new Date().toISOString().slice(0, 10)}.md`;
  
  triggerFileDownload(blob, filename);
  return filename;
}

/**
 * Exports Jira Sprint Backlog payload JSON
 */
export function exportMOMToJiraJSON(meeting: Meeting): string {
  const jiraPayload = {
    projectKey: 'SYNC',
    meetingId: meeting.id,
    meetingTitle: meeting.title,
    syncedAt: new Date().toISOString(),
    sprintBacklog: meeting.actionItems.map((item, index) => ({
      issueType: 'Task',
      summary: item.title,
      description: `Originating from executive meeting: "${meeting.title}" on ${meeting.date}. Assigned audio coordinate: ${item.originTimestamp ? formatDuration(item.originTimestamp) : 'N/A'}`,
      priority: item.priority === 'high' ? 'High' : item.priority === 'medium' ? 'Medium' : 'Low',
      assigneeName: item.assignee,
      dueDate: item.dueDate,
      labels: ['meetsync-ai', meeting.department.toLowerCase(), 'action-item'],
      customFields: {
        customfield_10010: meeting.id,
        customfield_10011: item.id,
      },
    })),
    decisionsAuditLog: meeting.decisions.map((dec) => ({
      issueType: 'Decision-Record',
      code: dec.code,
      statement: dec.statement,
      status: dec.status,
      vectorDistance: dec.ragDistance,
      confidenceScore: dec.confidenceScore,
      citationQuote: dec.citationQuote,
      timestampSeconds: dec.citationTimestamp,
    })),
  };

  const content = JSON.stringify(jiraPayload, null, 2);
  const blob = new Blob([content], { type: 'application/json;charset=utf-8;' });
  const sanitizedTitle = meeting.title.replace(/[^a-zA-Z0-9_-]/g, '_');
  const filename = `${sanitizedTitle}_Jira_Sprint_Payload_${new Date().toISOString().slice(0, 10)}.json`;
  
  triggerFileDownload(blob, filename);
  return filename;
}

/**
 * Exports Executive MOM Brief formatted for printing / PDF saving
 */
export function exportMOMToPDF(meeting: Meeting): string {
  // Generate HTML for formatted executive brief print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${meeting.title} - Executive Minutes</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; line-height: 1.5; }
            h1 { color: #0f172a; border-bottom: 2px solid #00F9C7; padding-bottom: 8px; margin-bottom: 4px; }
            .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
            h2 { color: #0284c7; margin-top: 24px; font-size: 18px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
            th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
            th { background: #f1f5f9; font-weight: 600; }
            blockquote { background: #f8fafc; border-left: 3px solid #0284c7; margin: 12px 0; padding: 10px 14px; font-style: italic; color: #334155; }
            .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 11px; font-weight: bold; background: #e0f2fe; color: #0369a1; }
            @media print { body { padding: 10px; } }
          </style>
        </head>
        <body>
          <h1>${meeting.title}</h1>
          <div class="meta">
            ${meeting.date} · ${meeting.department} · Organizer: ${meeting.organizer} · Status: <strong>${meeting.status}</strong>
          </div>
          <h2>Executive Summary</h2>
          <p>${meeting.summary}</p>
          <h2>Key Strategic Takeaways</h2>
          <ul>
            ${meeting.keyTakeaways.map((t) => `<li>${t}</li>`).join('')}
          </ul>
          <h2>Action Items & Ownership</h2>
          <table>
            <thead>
              <tr><th>Task</th><th>Assignee</th><th>Priority</th><th>Due Date</th><th>Status</th></tr>
            </thead>
            <tbody>
              ${meeting.actionItems.map((a) => `<tr><td>${a.title}</td><td>${a.assignee}</td><td>${a.priority.toUpperCase()}</td><td>${a.dueDate}</td><td>${a.completed ? 'Completed' : 'Open'}</td></tr>`).join('')}
            </tbody>
          </table>
          <h2>Decision Traceability Matrix (RAG Audit)</h2>
          <table>
            <thead>
              <tr><th>Code</th><th>Decision Statement</th><th>Category</th><th>Confidence</th><th>Status</th></tr>
            </thead>
            <tbody>
              ${meeting.decisions.map((d) => `<tr><td><strong>${d.code}</strong></td><td>${d.statement}</td><td>${d.category}</td><td>${d.confidenceScore}%</td><td>${d.status}</td></tr>`).join('')}
            </tbody>
          </table>
          <h2>Citations & Evidence</h2>
          ${meeting.decisions.map((d) => `
            <div>
              <strong>${d.code}: ${d.statement}</strong> [Timestamp: ${formatDuration(d.citationTimestamp)}]
              <blockquote>"${d.citationQuote}"</blockquote>
            </div>
          `).join('')}
          <script>
            window.onload = function() { window.print(); };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }
  return 'PDF Brief Opened';
}
